








//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextTemplate
{
    public partial class ClientPage
    {

        public string ClientName
        {
            get
            {
                return _elementClientName;
            }
            set
            {
                _elementClientName = value;
            }
        }

    }
}
