//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextTemplate
{
    public partial class LoginPage
    {
        public string UserName
        {
            get
            {
                return _elementUserName;
            }
            set
            {
                _elementUserName = value;
            }
        }
        public string Password
        {
            get
            {
                return _elementPassword;
            }
            set
            {
                _elementPassword = value;
            }
        }
        public string IsRememberMe
        {
            get
            {
                return _elementIsRememberMe;
            }
            set
            {
                _elementIsRememberMe = value;
            }
        }
    }
}
